version: '3.6'
services:
  web: &app_base
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
    command: ['bundle', 'exec', 'puma', '-C', 'puma.rb']
    volumes:
      - bundle:/usr/local/bundle
      - .:/app
    working_dir: /app
    environment:
      - ISHOCON1_DB_BENCH_NAME=ishocon1_bench
      - ISHOCON1_DB_PORT=3306
      - ISHOCON1_DB_USER=root
      - ISHOCON1_DB_NAME=ishocon1
      - ISHOCON1_DB_HOST=db
      - ISHOCON1_DB_PASSWORD=test123
    stdin_open: true
    tty: true
    platform: linux/amd64
    depends_on:
      - db
  db:
    image: mysql:8.0
    platform: linux/amd64
    command:  --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: test123
    healthcheck:
      test:  mysql --password=test123 -e "show databases;"
    volumes:
     - dbdata:/var/lib/mysql
  redis:
    image: redis
volumes:
  dbdata:
  bundle:
